appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 9555
servicePort: 9555
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "9555"
resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi