appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 8080
servicePort: 5000
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "8080"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi