appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 3550
servicePort: 3550
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "3550"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi