appName: recommendationservice
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 8080
servicePort: 8080
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi