appName: redis-cart
appImage: public.ecr.aws/docker/library/redis
appVersion: latest
appReplicas: 1
containerPort: 6379
servicePort: 6379
serviceType: ClusterIP
volumeName: redis-data
containerMountPath: /data
resources:
  requests:
    cpu: 70m
    memory: 200Mi
  limits:
    cpu: 125m
    memory: 256Mi